# **DIVA OCTAVIANI - 2311102006**

### **Twitter Authentication Token**

In [ ]:
twitter_auth_token = "a58079d301fded8089a6e24a2de6210a8dd29124"

### **Install Library**

In [ ]:
# Pandas untuk pengolahan data
!pip install pandas

# update package list
!sudo apt-get update

# install dependencies
!sudo apt-get install -y ca-certificates curl gnupg

# membuat folder keyring untuk repository
!sudo mkdir -p /etc/apt/keyrings

# download key repository Node.js
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

# menambahkan repository Node.js
!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

# update repository
!sudo apt-get update

# install Node.js
!sudo apt-get install nodejs -y

# cek versi Node.js
!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://deb.nodesource.com/node_24.x nodistro InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.23).
gnupg is already the newest version (2.2.27-3ubuntu2.5).
0 upgraded, 0 newly installed, 0 to remove and 93 not upgraded.
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://cli.github.com/packages stable InRelease
Get:3 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Hit:4 https://deb.nodesource.com/node_24.x nodistro InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:8 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [14.0 kB]
Hit:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 26.1 kB in 1s (20.5 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (24.14.0-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 93 not upgraded.
v24.14.0

In [ ]:
# install playwright dependencies
!npx playwright install-deps

⠙⠹⠸⠼⠴⠦Installing dependencies...
Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:7 https://deb.nodesource.com/node_24.x nodistro InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Hit:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-freefont-ttf is already the newest version (20120503-10build1).
fonts-liberation is already the newest version (1:1.07.4-11).
libatk-bridge2.0-0 is already the newest version (2.38.0-3).
libatk1.0-0 is already the newest version (2.36.0-3build1).
libatspi2.0-0 is already the newest version (2.44.0-3).
libcairo-gobject2 is already the newest version (1.16.0-5ubuntu2).
libcairo2 is already the newest version (1.16.0-5ubuntu2).
libdbus-glib-1-2 is already the newest version (0.112-2build1).
libegl1 is already the newest version (1.4.0-1).
libenchant-2-2 is already the newest version (2.3.2-1ubuntu2).
libepoxy0 is already the newest version (1.5.10-1).
libevdev2 is already the newest version (1.12.1+dfsg-1).
libevent-2.1-7 is already the newest version (2.1.12-stable-1build3).
libfontconfig1 is already the newest version (2.13.1-4.2ubuntu5).
libgles2 is already the newest version (1.4.0-1).
libglx0 is already the newest version (1.4.0-1).
libgudev-1.0-0 is already the newest version (1:237-2build1).
libhyphen0 is already the newest version (2.8.8-7build2).
libicu70 is already the newest version (70.1-2).
libjpeg-turbo8 is already the newest version (2.1.2-0ubuntu1).
liblcms2-2 is already the newest version (2.12~rc1-2build2).
libmanette-0.2-0 is already the newest version (0.2.6-3build1).
libopengl0 is already the newest version (1.4.0-1).
libopus0 is already the newest version (1.3.1-0.1build2).
libproxy1v5 is already the newest version (0.4.17-2).
libsecret-1-0 is already the newest version (0.20.5-2).
libwoff1 is already the newest version (1.0.2-1build4).
libxcb-shm0 is already the newest version (1.14-3ubuntu3).
libxcb1 is already the newest version (1.14-3ubuntu3).
libxcomposite1 is already the newest version (1:0.4.5-1build2).
libxcursor1 is already the newest version (1:1.2.0-2build4).
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxext6 is already the newest version (2:1.3.4-1build1).
libxfixes3 is already the newest version (1:6.0.0-1).
libxi6 is already the newest version (2:1.8-1build1).
libxkbcommon0 is already the newest version (1.4.0-1).
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrender1 is already the newest version (1:0.9.10-1build4).
libxtst6 is already the newest version (2:1.2.3-1build4).
xfonts-scalable is already the newest version (1:1.0.3-1.2ubuntu1).
fonts-ipafont-gothic is already the newest version (00303-21ubuntu1).
fonts-tlwg-loma-otf is already the newest version (1:0.7.3-1).
fonts-unifont is already the newest version (1:14.0.01-1).
fonts-wqy-zenhei is already the newest version (0.9.45-8).
libavif13 is already the newest version (0.9.3-3).
libffi7 is already the newest version (3.3-5ubuntu1).
libx264-163 is already the newest version (2:0.163.3060+git5db6aa6-2build1).
xfonts-cyrillic is already the newest version (1:1.0.5).
fonts-noto-color-emoji is already the newest version (2.047-0ubuntu0.22.04.1).
gstreamer1.0-plugins-base is already the newest version (1.20.1-1ubuntu0.5).
gstreamer1.0-plugins-good is already the newest version (1.20.3-0ubuntu1.4).
libasound2 is already the newest version (1.2.6.1-1ubuntu1.1).
libasound2 set to manually installed.
libatomic1 is already the newest version (12.3.0-1ubuntu1~22.04.3).
libatomic1 set to manually installed.
libcups2 is already the newest version (2.4.1op1-1ubuntu4.16).
libdbus-1-3 is already the newest version (1.12.20-2ubuntu4.1).
libdrm2 is already the newest version (2.4.113-2~ubuntu0.22.04.1).
libfreetype6 is already the newest version (2.11.1+dfsg-1ubuntu0.3).
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgdk-pixbuf-2.0-0 is already the newest version (2.42.8+dfsg-1ubuntu0.4).
libglib2.0-0 is already the newest version (2.72.4-0ubuntu2.9).
libgstreamer-gl1.0-0 is already the newest version (1.20.1-1ubuntu0.5).
libgstreamer-plugins-base1.0-0 is already the newest version (1.20.1-1ubuntu0.5).
libgstreamer1.0-0 is already the newest version (1.20.3-0ubuntu1.1).
libgtk-3-0 is already the newest version (3.24.33-1ubuntu2.2).
libgtk-4-1 is already the newest version (4.6.9+ds-0ubuntu0.22.04.2).
libharfbuzz-icu0 is already the newest version (2.7.4-1ubuntu3.2).
libharfbuzz0b is already the newest version (2.7.4-1ubuntu3.2).
libnotify4 is already the newest version (0.7.9-3ubuntu5.22.04.1).
libnspr4 is already the newest version (2:4.35-0ubuntu0.22.04.1).
libnss3 is already the newest version (2:3.98-0ubuntu0.22.04.3).
libnss3 set to manually installed.
libopenjp2-7 is already the newest version (2.4.0-6ubuntu0.4).
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpangocairo-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpng16-16 is already the newest version (1.6.37-3ubuntu0.4).
libpng16-16 set to manually installed.
libwayland-client0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-egl1 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-server0 is already the newest version (1.20.0-1ubuntu0.1).
libwebpdemux2 is already the newest version (1.2.2-2ubuntu0.22.04.2).
libx11-6 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-xcb1 is already the newest version (2:1.7.5-1ubuntu0.3).
libxml2 is already the newest version (2.9.13+dfsg-1ubuntu0.11).
libxml2 set to manually installed.
libxslt1.1 is already the newest version (1.1.34-4ubuntu0.22.04.5).
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
gstreamer1.0-libav is already the newest version (1.20.3-0ubuntu1).
gstreamer1.0-plugins-bad is already the newest version (1.20.3-0ubuntu1.1).
libsoup-3.0-0 is already the newest version (3.0.7-0ubuntu1).
xvfb is already the newest version (2:21.1.4-2ubuntu1.7~22.04.16).
0 upgraded, 0 newly installed, 0 to remove and 93 not upgraded.
⠙

### **Scraping Data Tweet**

In [ ]:
filename = 'scraping_x_korupsi.csv'
search_keyword = 'korupsi'
limit = 1100

# jalankan tool tweet-harvest untuk scraping tweet
!npx -y tweet-harvest@latest -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.7.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/scraping_x_korupsi.csv, renaming to ./tweets-data/scraping_x_korupsi.old.csv

-- Scrolling... (1) (2) (3) (4)
Filling in keywords: korupsi

 (5)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 20


Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 40

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 60

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 80

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 100

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 120

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 140

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 160

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 180

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 200

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 220

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 240

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 260

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 280

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 300

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 320

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 340

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 360

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 380

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 400

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 420

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 440

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 460

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 480

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 500

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 520

-- Scrolling... (1) (2) (3) (4) (5) (6)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 540

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 560

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 580

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 600

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 620

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 640

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 660

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 680

-- Scrolling... (1) (2) (3) (4) (5)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 700

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 720

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 740

-- Scrolling... (1)[v2.7.1] Error parsing response json: {"_type":"Response","_guid":"response@b00675a2f1e2dae9cf3d9e95a3a656bc"}
[v2.7.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.7.1] Error parsing response json: {"_type":"Response","_guid":"response@bafb6bb4cff579cfa428eb29fc27cad3"}
[v2.7.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.7.1] Error parsing response json: {"_type":"Response","_guid":"response@085a9edcb2fd13934172982e5d4da745"}
[v2.7.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.7.1] Error parsing response json: {"_type":"Response","_guid":"response@ad8fc126cb48ed00fc965c0ccf717b41"}
[v2.7.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.7.1] Error parsing response json: {"_type":"Response","_guid":"response@9db48519b95347ba427290709eceea3a"}
[v2.7.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.7.1] Error parsing response json: {"_type":"Response","_guid":"response@2c3dc5063b3d0dc220c4f071295619be"}
[v2.7.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.7.1] Error parsing response json: {"_type":"Response","_guid":"response@da49e50e31f0c16b54762f853154fd51"}
[v2.7.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.7.1] Error parsing response json: {"_type":"Response","_guid":"response@c7f1e45856416e51e7d216a6b6b5c0d4"}
[v2.7.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.7.1] Error parsing response json: {"_type":"Response","_guid":"response@45b03f95b664635f4982908f6fa70f7a"}
[v2.7.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.7.1] Error parsing response json: {"_type":"Response","_guid":"response@9fe8afc70c62f943beb2308b5a41ffa6"}
[v2.7.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.


Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 760

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 780

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 800

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 820

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 840

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 860


Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 880

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 900

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 920

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 940

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 960

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 980

-- Scrolling... (1) (2) (3) (4) (5) (6)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 1000

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 1020

-- Scrolling... (1) (2) (3) (4) (5) (6) (7)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 1040

-- Scrolling... (1) (2) (3) (4) (5) (6) (7)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 1060

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 1080

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/scraping_x_korupsi.csv
Total tweets saved: 1100
Got 1100 tweets, done scrolling...
⠙

### **File Hasil Scraping**

In [ ]:
import pandas as pd

# path file hasil scraping
file_path = "/content/tweets-data/scraping_x_korupsi.csv"

# membaca file CSV
df = pd.read_csv(file_path)

# menampilkan data
display(df)

      conversation_id_str                created_at  favorite_count  \
0     2031765638545568164  2026-03-12T05:10:25.000Z               0
1     2031960908428427710  2026-03-12T05:10:07.000Z               0
2     2031678225345360064  2026-03-12T05:08:33.000Z               0
3     2031742182940708986  2026-03-12T05:07:50.000Z               1
4     2031678225345360064  2026-03-12T05:06:11.000Z               0
5     2031853951620931953  2026-03-12T05:05:11.000Z               0
6     2031959338806644751  2026-03-12T05:04:06.000Z               0
7     2031959338806644751  2026-03-12T05:03:57.000Z               0
8     2030930969860124848  2026-03-12T05:03:19.000Z               0
9     2031959105448133044  2026-03-12T05:02:57.000Z               0
10    2031959044014133346  2026-03-12T05:02:42.000Z               0
11    2031678225345360064  2026-03-12T05:02:36.000Z               0
12    2031958868193153317  2026-03-12T05:02:00.000Z               0
13    2031958866746097700  2026-03-12T05:02:00.000Z               0
14    2031958462457102603  2026-03-12T05:00:24.000Z               0
15    2031958364809494660  2026-03-12T05:00:00.000Z               0
16    2031725603540660668  2026-03-12T04:59:54.000Z               0
17    2031926854274420966  2026-03-12T04:59:34.000Z               0
18    2031926854274420966  2026-03-12T04:59:11.000Z               0
19    2031926854274420966  2026-03-12T04:58:34.000Z               0
20    2031935886011822307  2026-03-12T04:58:33.000Z               0
21    2031957351977402677  2026-03-12T04:55:59.000Z               2
22    2031790702963912905  2026-03-12T04:54:57.000Z               0
23    2031722884016869652  2026-03-12T04:54:35.000Z               0
24    2031678225345360064  2026-03-12T04:54:07.000Z               1
25    2031956790578201075  2026-03-12T04:53:45.000Z               0
26    2031765638545568164  2026-03-12T04:53:11.000Z               0
27    2031956405775974562  2026-03-12T04:52:13.000Z               0
28    2031604832486961477  2026-03-12T04:51:55.000Z               0
29    2031956314092716106  2026-03-12T04:51:51.000Z               0
30    2031956310166815078  2026-03-12T04:51:50.000Z               0
31    2031765638545568164  2026-03-12T04:51:10.000Z               0
32    2031956130260533289  2026-03-12T04:51:08.000Z               0
33    2031949051193704452  2026-03-12T04:50:36.000Z               0
34    2031948728605753448  2026-03-12T04:49:59.000Z               0
35    2031955304402055377  2026-03-12T04:47:51.000Z               1
36    2031926854274420966  2026-03-12T04:47:22.000Z               0
37    2031610745327390913  2026-03-12T04:46:24.000Z               1
38    2031678225345360064  2026-03-12T04:45:33.000Z               0
39    2031954478828843500  2026-03-12T04:44:34.000Z               0
40    2031638824871407923  2026-03-12T04:30:26.000Z               0
41    2031926854274420966  2026-03-12T04:30:01.000Z               1
42    2031679564330782861  2026-03-12T04:30:00.000Z               0
43    2031185617242173545  2026-03-12T04:28:25.000Z               0
44    2031946320907550789  2026-03-12T04:28:12.000Z               0
45    2031768835272176123  2026-03-12T04:28:11.000Z               0
46    2031950225422893566  2026-03-12T04:27:44.000Z               0
47    2031950225422893566  2026-03-12T04:27:40.000Z               0
48    2031185617242173545  2026-03-12T04:27:18.000Z               0
49    2031185617242173545  2026-03-12T04:25:33.000Z               0
50    2031922260463022334  2026-03-12T04:25:31.000Z               0
51    2031949588933046560  2026-03-12T04:25:08.000Z               0
52    2031949552425844842  2026-03-12T04:24:59.000Z               9
53    2031899174837633201  2026-03-12T04:24:50.000Z               0
54    2031768835272176123  2026-03-12T04:24:34.000Z               0
55    2031185617242173545  2026-03-12T04:24:31.000Z               0
56    2031765638545568164  2026-03-12T04:24:23.000Z               0
57    2031922260463022334  2026-03-12T04:23:22.000Z               0
58    2031710819554320515  2026-03-12T04:23:20.000Z               0
59    2031949126209057192  2026-03-12T04:23:18.000Z               0
60    2031945853750100059  2026-03-12T04:23:08.000Z               0
61    2031587427400429867  2026-03-12T04:22:25.000Z               0
62    2031896421679710618  2026-03-12T04:22:20.000Z               1
63    2031926854274420966  2026-03-12T04:21:56.000Z               3
64    2031645632818209246  2026-03-12T04:21:36.000Z               0
65    2031948355958665262  2026-03-12T04:20:14.000Z               0
66    2031926854274420966  2026-03-12T04:20:12.000Z               0
67    2031948130510651578  2026-03-12T04:19:20.000Z               0
68    2031948074004988029  2026-03-12T04:19:07.000Z               2
69    2031637514214322460  2026-03-12T04:18:47.000Z               1
70    2031391822132773045  2026-03-12T04:17:36.000Z               0
71    2031567559217328272  2026-03-12T04:11:30.000Z               0
72    2031945884146278616  2026-03-12T04:10:25.000Z               0
73    2031945322512204214  2026-03-12T04:08:11.000Z               0
74    2031765638545568164  2026-03-12T04:06:54.000Z               0
75    2031725603540660668  2026-03-12T04:06:31.000Z               0
76    2031641390560534808  2026-03-12T04:05:57.000Z               0
77    2031902420394262532  2026-03-12T04:04:57.000Z               1
78    2030685975282864420  2026-03-12T04:03:58.000Z               0
79    2031185617242173545  2026-03-12T04:03:55.000Z               0
80    2031940657166639538  2026-03-12T03:49:38.000Z              10
81    2031609115034923118  2026-03-12T03:46:25.000Z               1
82    2009617397255409941  2026-03-12T03:45:51.000Z               0
83    2031742506170519768  2026-03-12T03:44:16.000Z               0
84    2031737155517833352  2026-03-12T03:43:51.000Z               1
85    2031672765061955740  2026-03-12T03:42:49.000Z               0
86    2031902550677733394  2026-03-12T03:42:27.000Z               0
87    2031904396309848380  2026-03-12T03:41:08.000Z               0
88    2031740715957682416  2026-03-12T03:40:29.000Z               0
89    2031554426125816231  2026-03-12T03:40:21.000Z               0
90    2031709338533011745  2026-03-12T03:39:42.000Z               0
91    2031937732445159513  2026-03-12T03:38:01.000Z               0
92    2031937415611630030  2026-03-12T03:36:46.000Z               0
93    2031567559217328272  2026-03-12T03:36:39.000Z               0
94    2029430589200449614  2026-03-12T03:36:01.000Z               0
95    2031567305172463850  2026-03-12T03:35:43.000Z               0
96    2031937123872620979  2026-03-12T03:35:36.000Z               0
97    2031652328047260071  2026-03-12T03:35:24.000Z               0
98    2031936479828852830  2026-03-12T03:33:03.000Z               0
99    2031307208823288133  2026-03-12T03:32:19.000Z               0
100   2031725603540660668  2026-03-12T03:32:10.000Z               1
101   2031935869138223298  2026-03-12T03:30:49.000Z               0
102   2031935855510897113  2026-03-12T03:30:34.000Z               0
103   2031929684544626986  2026-03-12T03:28:54.000Z               0
104   2031935077387813266  2026-03-12T03:27:28.000Z               0
105   2031934848336871459  2026-03-12T03:26:34.000Z               0
106   2031706338393559547  2026-03-12T03:26:13.000Z               0
107   2031740205783466322  2026-03-12T03:25:36.000Z               0
108   2031765638545568164  2026-03-12T03:25:13.000Z               0
109   2031933860712522188  2026-03-12T03:22:38.000Z               0
110   2031933779607236977  2026-03-12T03:22:19.000Z               0
111   2031933578804937209  2026-03-12T03:21:31.000Z              25
112   2031852877745180743  2026-03-12T03:19:33.000Z               0
113   2031933008543171061  2026-03-12T03:19:15.000Z               2
114   2031604832486961477  2026-03-12T03:19:15.000Z               0
115   2031725603540660668  2026-03-12T03:18:52.000Z               0
116   2031811269976891610  2026-03-12T03:18:39.000Z               0
117   2031932559492595774  2026-03-12T03:17:28.000Z               1
118   2031932357994037430  2026-03-12T03:16:40.000Z               1
119   2031638824871407923  2026-03-12T03:15:24.000Z               0
120   2031725603540660668  2026-03-12T02:32:14.000Z               0
121   2031920901856641166  2026-03-12T02:31:08.000Z               1
122   2031920614471319628  2026-03-12T02:30:00.000Z               1
123   2031692723053576670  2026-03-12T02:29:52.000Z               0
124   2031765638545568164  2026-03-12T02:29:43.000Z               0
125   2031717547809337350  2026-03-12T02:29:09.000Z               1
126   2031725603540660668  2026-03-12T02:29:04.000Z               0
127   2031725603540660668  2026-03-12T02:28:38.000Z               0
128   2031571826711896094  2026-03-12T02:26:06.000Z               0
129   2030958533936914492  2026-03-12T02:25:57.000Z               0
130   2031678225345360064  2026-03-12T02:24:42.000Z               0
131   2031918006608306515  2026-03-12T02:19:38.000Z               0
132   2031207883275489385  2026-03-12T02:17:37.000Z               0
133   2031917286492364995  2026-03-12T02:16:46.000Z               0
134   2031917068078236047  2026-03-12T02:15:54.000Z               0
135   2031725603540660668  2026-03-12T02:14:46.000Z               1
136   2031916634752106805  2026-03-12T02:14:11.000Z               0
137   2031724561704911033  2026-03-12T02:11:42.000Z               0
138   2031915694384955450  2026-03-12T02:10:27.000Z               0
139   2031915616450592916  2026-03-12T02:10:08.000Z               0
140   2031765638545568164  2026-03-12T02:08:57.000Z               0
141   2031690022953603184  2026-03-12T02:08:33.000Z               0
142   2031915090010841188  2026-03-12T02:08:03.000Z               0
143   2031622010867261924  2026-03-12T02:06:55.000Z               0
144   2031904658940428406  2026-03-12T02:06:30.000Z               0
145   2031740205783466322  2026-03-12T02:04:37.000Z               0
146   2031913774559740227  2026-03-12T02:02:49.000Z               1
147   2031676381650923748  2026-03-12T02:00:01.000Z               0
148   2031912873472246052  2026-03-12T01:59:14.000Z               0
149   2031249390955118818  2026-03-12T01:54:10.000Z               0
150   2031845983458578865  2026-03-12T01:52:45.000Z               0
151   2031742988762894800  2026-03-12T01:52:27.000Z               0
152   2031568733697876064  2026-03-12T01:52:12.000Z               0
153   2031906604757762510  2026-03-12T01:50:47.000Z               2
154   2031906604757762510  2026-03-12T01:48:17.000Z               2
155   2031584861677560101  2026-03-12T01:45:58.000Z               0
156   2031909289435283732  2026-03-12T01:45:00.000Z               0
157   2031908896156369120  2026-03-12T01:43:26.000Z               0
158   2031908779298865513  2026-03-12T01:42:58.000Z               1
159   2031908639976706091  2026-03-12T01:42:25.000Z               0
160   2031908471332089858  2026-03-12T01:41:45.000Z               0
161   2031908252670378384  2026-03-12T01:40:53.000Z               0
162   2031908148416823645  2026-03-12T01:40:28.000Z               0
163   2031742182940708986  2026-03-12T01:37:57.000Z               3
164   2031907478750052607  2026-03-12T01:37:48.000Z               0
165   2031639130200060320  2026-03-12T01:37:36.000Z               1
166   2031903738890502410  2026-03-12T01:37:31.000Z               0
167   2031734047895134689  2026-03-12T01:37:03.000Z               0
168   2031732740169814037  2026-03-12T01:36:48.000Z               0
169   2031907067116806428  2026-03-12T01:36:10.000Z               0
170   2031810078500929623  2026-03-12T01:34:45.000Z               6
171   2031823096274194878  2026-03-12T01:34:45.000Z               0
172   2031249390955118818  2026-03-12T01:32:54.000Z               0
173   2031765638545568164  2026-03-12T01:32:44.000Z               0
174   2031746525643329658  2026-03-12T01:31:35.000Z               0
175   2031725603540660668  2026-03-12T01:29:59.000Z               0
176   2031580307271655494  2026-03-12T01:28:43.000Z               0
177   2031725603540660668  2026-03-12T01:26:43.000Z               0
178   2031904674245218807  2026-03-12T01:26:39.000Z               0
179   2031638824871407923  2026-03-12T01:25:40.000Z               0
180   2031904359949181023  2026-03-12T01:25:25.000Z               0
181   2031676381650923748  2026-03-12T01:24:39.000Z               1
182   2031849126477119964  2026-03-12T01:23:22.000Z               0
183   2031903738890502410  2026-03-12T01:22:56.000Z               0
184   2031903704379687359  2026-03-12T01:22:48.000Z               0
185   2031903558711304482  2026-03-12T01:22:13.000Z               0
186   2031903539761725618  2026-03-12T01:22:09.000Z               0
187   2031584861677560101  2026-03-12T01:21:48.000Z               2
188   2031783134812090860  2026-03-12T01:20:58.000Z               6
189   2031835129782682051  2026-03-12T01:20:27.000Z               0
190   2031059054131556785  2026-03-12T01:19:18.000Z               0
191   2031604615633158518  2026-03-12T01:17:46.000Z               0
192   2031902126998159813  2026-03-12T01:16:32.000Z               0
193   2031901421684039767  2026-03-12T01:13:44.000Z               0
194   2031724561704911033  2026-03-12T01:12:38.000Z               0
195   2031249390955118818  2026-03-12T01:10:17.000Z               0
196   2031765638545568164  2026-03-12T01:07:23.000Z               9
197   2031604115303014441  2026-03-12T01:05:45.000Z               0
198   2031790702963912905  2026-03-12T01:05:05.000Z               0
199   2031898867969687859  2026-03-12T01:03:35.000Z               1
200   2031711502009508221  2026-03-12T00:26:23.000Z               0
201   2031744956499657196  2026-03-12T00:25:04.000Z               0
202   2031258535162687978  2026-03-12T00:22:22.000Z               0
203   2031888246993797360  2026-03-12T00:21:23.000Z               0
204   2031730607852822712  2026-03-12T00:20:28.000Z               3
205   2031887898103198119  2026-03-12T00:20:00.000Z               1
206   2031753684338761785  2026-03-12T00:17:19.000Z               0
207   2031740715957682416  2026-03-12T00:16:36.000Z               0
208   2031357263441702981  2026-03-12T00:16:05.000Z               0
209   2031725603540660668  2026-03-12T00:16:03.000Z               0
210   2031886498552037727  2026-03-12T00:14:26.000Z               0
211   2031575864316436803  2026-03-12T00:13:21.000Z               0
212   2031644451878416471  2026-03-12T00:13:18.000Z               0
213   2031885925152919667  2026-03-12T00:12:09.000Z               0
214   2031885867384783230  2026-03-12T00:11:56.000Z               0
215   2031725603540660668  2026-03-12T00:11:27.000Z               0
216   2031881964639375389  2026-03-12T00:10:59.000Z               0
217   2031623637854466191  2026-03-12T00:09:01.000Z               0
218   2030065553541582996  2026-03-12T00:08:00.000Z               0
219   2031290266309509243  2026-03-12T00:07:08.000Z               0
220   2031651618798842358  2026-03-11T23:41:08.000Z               0
221   2031725603540660668  2026-03-11T23:40:04.000Z               0
222   2031877665729454145  2026-03-11T23:39:20.000Z               0
223   2031750642629251321  2026-03-11T23:37:58.000Z               0
224   2031877070075383987  2026-03-11T23:36:58.000Z               1
225   2031876341298246095  2026-03-11T23:34:04.000Z               0
226   2031764116646379674  2026-03-11T23:31:36.000Z               1
227   2031750642629251321  2026-03-11T23:30:47.000Z               0
228   2031875148232736841  2026-03-11T23:29:20.000Z               0
229   2031744956499657196  2026-03-11T23:29:17.000Z               0
230   2031697217321673124  2026-03-11T23:23:13.000Z               7
231   2031873350633689226  2026-03-11T23:22:11.000Z               0
232   2031641351281070327  2026-03-11T23:19:21.000Z               0
233   2031291216088936817  2026-03-11T23:17:51.000Z               0
234   2031720532698444006  2026-03-11T23:17:40.000Z               0
235   2031608564964536571  2026-03-11T23:15:24.000Z               0
236   2031651618798842358  2026-03-11T23:15:18.000Z               0
237   2031871371387740463  2026-03-11T23:14:19.000Z               0
238   2031869918740992103  2026-03-11T23:08:33.000Z               0
239   2031746284202430589  2026-03-11T23:06:26.000Z               0
240   2031725603540660668  2026-03-11T23:05:26.000Z               0
241   2031612621234003975  2026-03-11T23:03:53.000Z               0
242   2031866930324443217  2026-03-11T22:56:41.000Z               0
243   2031866225673064916  2026-03-11T22:53:53.000Z               5
244   2031866110015127687  2026-03-11T22:53:25.000Z               0
245   2031059054131556785  2026-03-11T22:52:35.000Z               0
246   2031862632731513271  2026-03-11T22:50:11.000Z               0
247   2031725603540660668  2026-03-11T22:50:01.000Z               2
248   2031864958976475194  2026-03-11T22:48:51.000Z              20
249   2030685975282864420  2026-03-11T22:48:11.000Z               0
250   2031864267444797606  2026-03-11T22:46:06.000Z               0
251   2031591446382616931  2026-03-11T22:45:42.000Z               0
252   2029544031483490749  2026-03-11T22:43:44.000Z               0
253   2031863664861725179  2026-03-11T22:43:42.000Z               1
254   2031222685112610993  2026-03-11T22:42:08.000Z               0
255   2031198220953727150  2026-03-11T22:41:02.000Z               0
256   2031862732727697502  2026-03-11T22:40:00.000Z               0
257   2031169057135931805  2026-03-11T22:39:12.000Z               1
258   2031725155341550000  2026-03-11T22:37:37.000Z               0
259   2031835129782682051  2026-03-11T22:36:48.000Z               0
260   2031746664931926514  2026-03-11T22:35:19.000Z               1
261   2031746284202430589  2026-03-11T22:35:02.000Z               0
262   2031169057135931805  2026-03-11T22:33:31.000Z               1
263   2031723648462258682  2026-03-11T22:32:58.000Z               0
264   2031725603540660668  2026-03-11T22:31:37.000Z               0
265   2031518371746115880  2026-03-11T22:31:12.000Z               0
266   2031835106722406715  2026-03-11T22:28:42.000Z               0
267   2031765638545568164  2026-03-11T22:27:45.000Z               4
268   2031390687137247703  2026-03-11T22:25:05.000Z               0
269   2031653465936859400  2026-03-11T22:23:24.000Z               0
270   2031635232508752367  2026-03-11T22:23:09.000Z               3
271   2031718779936551271  2026-03-11T22:21:34.000Z              10
272   2031658155978162327  2026-03-11T22:17:20.000Z               0
273   2031674069557657726  2026-03-11T22:16:36.000Z               1
274   2031751771610333324  2026-03-11T22:07:22.000Z               0
275   2031218574245900683  2026-03-11T22:06:48.000Z               0
276   2031854354643501101  2026-03-11T22:06:42.000Z               0
277   2031547959029149873  2026-03-11T22:05:00.000Z               0
278   2031364919707447360  2026-03-11T22:04:24.000Z               0
279   2031853465715331558  2026-03-11T22:03:10.000Z               0
280   2031707230664552533  2026-03-11T21:39:39.000Z               0
281   2031734047895134689  2026-03-11T21:39:07.000Z               0
282   2031452809380638924  2026-03-11T21:38:32.000Z               0
283   2031579815627862520  2026-03-11T21:37:52.000Z               0
284   2031846912358564347  2026-03-11T21:37:08.000Z               0
285   2031641314823962634  2026-03-11T21:36:48.000Z               0
286   2031580644548170225  2026-03-11T21:34:44.000Z               0
287   2031666862262735213  2026-03-11T21:31:53.000Z               0
288   2031701682380480683  2026-03-11T21:31:11.000Z               1
289   2031845303847174598  2026-03-11T21:30:44.000Z               0
290   2031678225345360064  2026-03-11T21:30:15.000Z               0
291   2031672765061955740  2026-03-11T21:30:14.000Z               0
292   2030862928073859350  2026-03-11T21:28:47.000Z               0

### **Kolom Terpilih**

In [ ]:
data_x = df[[
    "username",
    "full_text",
    "created_at",
    "favorite_count",
    "retweet_count"
]]

data_x.columns = [
    "Username",
    "Isi Tweet",
    "Tanggal Tweet",
    "Jumlah Like",
    "Jumlah Retweet"
]

display(data_x)

,Username,Isi Tweet,Tanggal Tweet,Jumlah Like,Jumlah Retweet
0,ChandraMan7679,@ImamBesar212 China komunis terapkan hukuman m...,2026-03-12T05:10:25.000Z,0,0
1,jus_alpukat97,Maling gak usah dikasih hati\n\nhttps://t.co/O...,2026-03-12T05:10:07.000Z,0,0
2,BosWagu,@IndonesiaFedera @Pakde_ian Cek dulu peraturan...,2026-03-12T05:08:33.000Z,0,0
3,chandratitius,"@ArvinHonami Iya, baru kepikiran Danantara mel...",2026-03-12T05:07:50.000Z,1,0
4,iyankecil0,@IndonesiaFedera dia korupsi kouta haji loh an...,2026-03-12T05:06:11.000Z,0,0
5,micielaandressa,@enginafess makan fuit korupsi juga bang?,2026-03-12T05:05:11.000Z,0,0
6,lehon_mangolu,Transformasi Bea Cukai adalah langkah nyata me...,2026-03-12T05:04:06.000Z,0,0
7,lehon_mangolu,Presiden Prabowo mendorong agar digitalisasi s...,2026-03-12T05:03:57.000Z,0,0
8,leeminhogita,@Franken_blues Ccok lah drpd PSI yg ccok gbing...,2026-03-12T05:03:19.000Z,0,0
9,jeep_jeff_jip,Korupsi untuk membeli gaya hidup,2026-03-12T05:02:57.000Z,0,0
10,seketikanet,Bupati aktif kembali diciduk KPK. Diduga ada i...,2026-03-12T05:02:42.000Z,0,0
11,ikn1890947,@IndonesiaFedera Belum ada keputusan terkait k...,2026-03-12T05:02:36.000Z,0,0
12,callmeopaaa,mbg adalah program terjelek ladang korupsi dan...,2026-03-12T05:02:00.000Z,0,0
13,Rikimuslimlogo,Yg aku masih ga ngerti tuh gunanya dapur mbg b...,2026-03-12T05:02:00.000Z,0,0
14,bnnkabmusirawas,Sosialisasi Zona Integritas Menuju Wilayah Be...,2026-03-12T05:00:24.000Z,0,0
15,politiknesiacom,Eks Bupati Lampung Timur Dawam Rahardjo Divoni...,2026-03-12T05:00:00.000Z,0,0
16,rudi_albantani,@UmarHasibuan__ @KPK_RI Menuduh seseorang koru...,2026-03-12T04:59:54.000Z,0,0
17,fckmylife17_,@KangManto123 MBG bermanfaat buat orang yg suk...,2026-03-12T04:59:34.000Z,0,0
18,Tonyawa69,"@KangManto123 BPJS sama TOL, banyak benefit da...",2026-03-12T04:59:11.000Z,0,0
19,BSafrinal,@KangManto123 Udah pasti BPJS. \n\nMBG itu han...,2026-03-12T04:58:34.000Z,0,0
20,KepriAswaja,@ainurohman Definisi bajingan sesungguhnya \n\...,2026-03-12T04:58:33.000Z,0,0
21,kompascom,Komisi Pemberantasan Korupsi (KPK) menyarankan...,2026-03-12T04:55:59.000Z,2,1
22,Marbun8Marbun,"@msaid_didu Bos,Republik ini tak akan maju,yak...",2026-03-12T04:54:57.000Z,0,0
23,awekensfox,@BosPurwa kebanggaan ormas paling nkri yang ke...,2026-03-12T04:54:35.000Z,0,0
24,ChanelUdin34091,@IndonesiaFedera ITULAH PENGIKUT² YG SUDAH TAK...,2026-03-12T04:54:07.000Z,1,1
25,djabrik76,Siapa saja bisa melakukan korupsi,2026-03-12T04:53:45.000Z,0,0
26,BiLAL_B1LL,"@ImamBesar212 Bukan masalah agamanya bro, masa...",2026-03-12T04:53:11.000Z,0,0
27,ATRBPN_TOBASA,"Halo #DonganATRBPNToba , Horas🙌\n.\n.\nTerimak...",2026-03-12T04:52:13.000Z,0,0
28,nanariyant62581,@LBH_Jakarta Naaahhh lagi ngumpul tuh anak Aba...,2026-03-12T04:51:55.000Z,0,0
29,YBahari92128,● KORUPSI DI BUMN - PT PALMCO - PT PERKEBUNANA...,2026-03-12T04:51:51.000Z,0,0
30,KN_Balikpapan,Persidangan Perkara Tindak Pidana Korupsi pada...,2026-03-12T04:51:50.000Z,0,0
31,GrosirJAMdanTAS,@YanSanaky @ImamBesar212 kristen islam ayo sep...,2026-03-12T04:51:10.000Z,0,0
32,radar_mojokerto,Komisi Pemberantasan Korupsi (KPK) mengatakan ...,2026-03-12T04:51:08.000Z,0,0
33,baco_djafa11377,@rimapurwasih Sakti korupsi?,2026-03-12T04:50:36.000Z,0,0
34,negativisme,"@PensilAajaib Ga usah bingung, korupsi aja bis...",2026-03-12T04:49:59.000Z,0,0
35,rysniro,"bpjs kerasa bgt sih, jalan tol juga jd cepet g...",2026-03-12T04:47:51.000Z,1,0
36,babananashh,@KangManto123 Jujur sih BPJS dan Jalan Tol yg ...,2026-03-12T04:47:22.000Z,0,0
37,FianHyde,"@ditanyaan udah gak bergizi, takaran ngasal, h...",2026-03-12T04:46:24.000Z,1,0
38,twittwittwitt16,@IndonesiaFedera N a U dzubillah ormas Nadah U...,2026-03-12T04:45:33.000Z,0,0
39,cyaasaurus,"Soalnya klo lanjut dikira korupsi, pdhl semua ...",2026-03-12T04:44:34.000Z,0,0
40,Sapuran6,"@narkosun Yg korupsi berdiri di belakang, samb...",2026-03-12T04:30:26.000Z,0,0
41,lightenlam,"@sarbennn @KangManto123 @r3tmono ""Kalo saya me...",2026-03-12T04:30:01.000Z,1,0
42,brekelele_,@NHenryp29864 Mbg adalah program terima kasih ...,2026-03-12T04:30:00.000Z,0,0
43,quis_alexi15970,"@johnpetrucci25 @musuhphp Kaya orang koar"" kor...",2026-03-12T04:28:25.000Z,0,0
44,BitterDie_,"@karirfess Gua bukan ngebela, tau gak kenapa n...",2026-03-12T04:28:12.000Z,0,0
45,Nostalgilabola,@KemenperinRI Mereka ga nganggap beliau korupsi,2026-03-12T04:28:11.000Z,0,0
46,MPraswadNugraha,"Selain itu, dalam tiga bulan pertama 2026, KPK...",2026-03-12T04:27:44.000Z,0,0
47,MPraswadNugraha,OTT lagi. Kepala daerah korupsi lagi.\n\nKPK m...,2026-03-12T04:27:40.000Z,0,0
48,quis_alexi15970,"@johnpetrucci25 @musuhphp Gw mau nanya 1,u tau...",2026-03-12T04:27:18.000Z,0,0
49,quis_alexi15970,@johnpetrucci25 @musuhphp Yg bilang orng indo ...,2026-03-12T04:25:33.000Z,0,0
50,Kiamat_Change,"@kompascom Korupsi itu dimulai dari Parpol, la...",2026-03-12T04:25:31.000Z,0,0
51,Oaakwood,"Kecil amat kacangnya, ini mah korupsi wkwkw",2026-03-12T04:25:08.000Z,0,0
52,thesmallmoney,Enak ya klo misal lulus SMA trus korupsi minim...,2026-03-12T04:24:59.000Z,9,0
53,springpetalia,@moonr1tz YA PERNAH LAH aku bukan anak pejabat...,2026-03-12T04:24:50.000Z,0,0
54,jakerajajowas,@KemenperinRI Ngezalimin orang tua dan kaum me...,2026-03-12T04:24:34.000Z,0,0
55,quis_alexi15970,@johnpetrucci25 @musuhphp Yah ente miss the wh...,2026-03-12T04:24:31.000Z,0,0
56,padangbelulang,@acestudent77 @bnababan @YanSanaky @ImamBesar2...,2026-03-12T04:24:23.000Z,0,0
57,Kiamat_Change,"@kompascom Indonesia didominansi hutan, gunung...",2026-03-12T04:23:22.000Z,0,0
58,Sweetyy199dy,@evanndeer Babi gemuk kebanyakan makan uang ko...,2026-03-12T04:23:20.000Z,0,0
59,wifejonginn,BERHENTI SELAMANYA AJA LADANG KORUPSI DOANK IN...,2026-03-12T04:23:18.000Z,0,0
60,saileurmoon,@tuesdaylilies ga korupsi bikin orang mati apa...,2026-03-12T04:23:08.000Z,0,0
61,tukangentahlah,@DS_yantie Indonesia kaya.\nBelanda ngejajah i...,2026-03-12T04:22:25.000Z,0,0
62,rsakulo77701,@Jelli_cent Semoga cepat tertangkap korupsi,2026-03-12T04:22:20.000Z,1,0
63,lightenlam,"@sarbennn @KangManto123 @r3tmono ""menghukum m4...",2026-03-12T04:21:56.000Z,3,0
64,smilefloweritme,@dosenkesmas Duhhh gw paham knpa merka begitu ...,2026-03-12T04:21:36.000Z,0,0
65,santri__,segera tahan para tersangka korupsi haji. \n@K...,2026-03-12T04:20:14.000Z,0,0
66,WahyuHaart,"@KangManto123 Pak beye juga pelopor e-ktp, mes...",2026-03-12T04:20:12.000Z,0,0
67,rudenimsby,Halo Sobat Mido! \nBerdasarkan hasil survei In...,2026-03-12T04:19:20.000Z,0,0
68,KompasTV,Hari Ini KPK Panggil Yaqut sebagai Tersangka K...,2026-03-12T04:19:07.000Z,2,1
69,oscarXoscar,"@paramariboi Bagi aku, melihat suatu kelompok ...",2026-03-12T04:18:47.000Z,1,0
70,lintang_ayoe,@sosmedkeras @hank_jkt Jd ingat korupsi simula...,2026-03-12T04:17:36.000Z,0,0
71,LukasWilhelm21,@Majelis_Ruhani Kenapa harus maksa sekuler kal...,2026-03-12T04:11:30.000Z,0,0
72,PDasamuka,Pak @prabowo menggaungkan pemberantasan korups...,2026-03-12T04:10:25.000Z,0,0
73,andrewenas,*Kepala Daerah Kunci Pemerataan Pembangunan: K...,2026-03-12T04:08:11.000Z,0,0
74,FakhrinNau89238,@YanSanaky @ImamBesar212 Kalo mau liat korupsi...,2026-03-12T04:06:54.000Z,0,0
75,Algusto_2025,@mangkleke @UmarHasibuan__ @KPK_RI Tersangka K...,2026-03-12T04:06:31.000Z,0,0
76,badutsbaduts,@GKuswaya Di negeri ini korupsi dan judol adal...,2026-03-12T04:05:57.000Z,0,0
77,inzhapt_76,@RakyatBerbisik Negeri penuh tipu daya dan kor...,2026-03-12T04:04:57.000Z,1,0
78,fajrioet,@zynxz333 @semangatdiriku aduh ini kenapa fans...,2026-03-12T04:03:58.000Z,0,0
79,quis_alexi15970,@BeenGoodSon @SphinxWyvern @musuhphp Nah kan k...,2026-03-12T04:03:55.000Z,0,0
80,are_inismyname,Maling Berkedok Gizi\nPresiden bodoh\nMenu MBG...,2026-03-12T03:49:38.000Z,10,7
81,LuckyLudjaina,@NHenryp29864 @GM_Warrios Negara komunis tp bs...,2026-03-12T03:46:25.000Z,1,0
82,massishal,@rimapurwasih Itu hidungnya asli atau sempalan...,2026-03-12T03:45:51.000Z,0,0
83,ayenhen,@makim4w @Anak__Ogi @great_fleet @pln_123 Baga...,2026-03-12T03:44:16.000Z,0,0
84,jepara123456,@JukiHoki 3 penyakit yg susah sembuh :\n\n1. K...,2026-03-12T03:43:51.000Z,1,0
85,_MonyetMetal,@kangdede78 Beliau mengira Negara ini sudah se...,2026-03-12T03:42:49.000Z,0,0
86,AliSahi59844570,"@SosmedAnu Fix suaminya korupsi Dana Keluarga,...",2026-03-12T03:42:27.000Z,0,0
87,adi461968,@NenkMonica Negara edan...korupsi yg terlalu t...,2026-03-12T03:41:08.000Z,0,0
88,Xyzjwge123,@DianSandiU mbg itu korupsi berjamaah,2026-03-12T03:40:29.000Z,0,0
89,sultanfrozen,@biaserubia @karirfess ((Mereka dapet duit ged...,2026-03-12T03:40:21.000Z,0,0
90,Slipkenyot,@kompascom Mending kasus korupsi haji diusut t...,2026-03-12T03:39:42.000Z,0,0
91,iyeyeline,Korupsi ada di manah2,2026-03-12T03:38:01.000Z,0,0
92,sanitamima,"Pekalongan citranya lagi ga bagus ini. Banjir,...",2026-03-12T03:36:46.000Z,0,0
93,EbiWanKenobi,@Majelis_Ruhani Ya penalaran mereka duit korup...,2026-03-12T03:36:39.000Z,0,0
94,CandraSury578,"@budimandjatmiko @prabowo @sahal Sahal, Prabow...",2026-03-12T03:36:01.000Z,0,0
95,herry_zudianto,@hanifproduktif Program MBG ... modus korupsi ...,2026-03-12T03:35:43.000Z,0,0
96,IDNTimesSulsel,Kejati Sulsel Tahan Tersangka Keenam Kasus Kor...,2026-03-12T03:35:36.000Z,0,0
97,adinp__,@myshawti Kalo ini kejadian pelakunya anak pej...,2026-03-12T03:35:24.000Z,0,0
98,wonyze,ew bgt korupsi kelas teri,2026-03-12T03:33:03.000Z,0,0
99,yossaa_,"@Prima199911 @VeronicaKoman Anjir idiot bgt, k...",2026-03-12T03:32:19.000Z,0,0
100,mat_teleng,@UmarHasibuan__ @KPK_RI Mengapa di paksakan da...,2026-03-12T03:32:10.000Z,1,1
101,lehon_mangolu,"Dalam kesempatan tersebut, Presiden Prabowo ju...",2026-03-12T03:30:49.000Z,0,0
102,sweetmiserys,"pdhl ga berbuat salah tp dihukum, gmn orang2 p...",2026-03-12T03:30:34.000Z,0,0
103,J0yoWi,@BosPurwa Korupsi = MISKOMUNIKASI\nKolusi = OK...,2026-03-12T03:28:54.000Z,0,0
104,KantahSibolga,Halo #SobATRBPN Sibolga\n.\noii Dusanak\n\nTer...,2026-03-12T03:27:28.000Z,0,0
105,redsheye,"Pantes para anjing itu merasa bebas korupsi, t...",2026-03-12T03:26:34.000Z,0,0
106,JuniartaPamudji,"@kompascom Gak mempan kl cm ancam2 aja, korups...",2026-03-12T03:26:13.000Z,0,0
107,DeblengSya44130,"@kompascom Jgn pake Gaji pak, Tinggal yg korup...",2026-03-12T03:25:36.000Z,0,0
108,sheilashthypcrt,@ImamBesar212 Korupsi di atas 10M ga boleh lan...,2026-03-12T03:25:13.000Z,0,0
109,liffitrindewor,WN I tiap hari dijejali dgn case korupsi pejab...,2026-03-12T03:22:38.000Z,0,0
110,Politikciki,Presiden Prabowo Subianto menegaskan komitmenn...,2026-03-12T03:22:19.000Z,0,0
111,lettachantik,Korupsi Kebun Binatang Surabaya...\n\nDi perki...,2026-03-12T03:21:31.000Z,25,7
112,untuN9ADsY,@BangPino__ proyek lahan korupsi...,2026-03-12T03:19:33.000Z,0,0
113,WongAlasRoban,Sebuah renungan :\n\n1. Ngomongnya anti korups...,2026-03-12T03:19:15.000Z,2,0
114,HanifRa050191,@LBH_Jakarta Anjir tiap ada program langsung t...,2026-03-12T03:19:15.000Z,0,0
115,ebbe1802,@UmarHasibuan__ @KPK_RI Semoga meletus balon h...,2026-03-12T03:18:52.000Z,0,0
116,AlesAlexios,@zoelfick Ada DPR zimbabwe bilang kaya gini be...,2026-03-12T03:18:39.000Z,0,0
117,Katherin_Mailoa,Kejaksaan Tinggi (Kejati) Maluku kembali menun...,2026-03-12T03:17:28.000Z,1,0
118,Katherin_Mailoa,Aliansi Peduli Lingkungan Maluku Utara di Jaka...,2026-03-12T03:16:40.000Z,1,0
119,bentedja,@narkosun Masalahnya agama gagal mencegah manu...,2026-03-12T03:15:24.000Z,0,0
120,Ikangmurapi11,@UmarHasibuan__ @KPK_RI Hukum seumur hidup dan...,2026-03-12T02:32:14.000Z,0,0
121,BPPMHKP_PRAYA,"Hai #SahabatBahari,\nBERSAMA LAWAN KORUPSI, TO...",2026-03-12T02:31:08.000Z,1,0
122,TirtoID,Polda Metro Jaya Tahan Dua Tersangka Korupsi d...,2026-03-12T02:30:00.000Z,1,0
123,IDRockstar_007,@LambeSahamjja Berantas korupsi &amp; para pel...,2026-03-12T02:29:52.000Z,0,0
124,anggita98087,@ImamBesar212 Emang yg sering ke Gereja gak ad...,2026-03-12T02:29:43.000Z,0,0
125,PRajagukgu38321,@__AnakKolong @AriefRohman_838 Menu edaaannn i...,2026-03-12T02:29:09.000Z,1,0
126,sin2023chan,"@UmarHasibuan__ @KPK_RI kalo ane, gimana caran...",2026-03-12T02:29:04.000Z,0,0
127,Eko72308133,@UmarHasibuan__ @KPK_RI Miskinkan sampai seaka...,2026-03-12T02:28:38.000Z,0,0
128,BruhGusGus,@RakyatBerbisik Lebih tepatnya membongkar AIB ...,2026-03-12T02:26:06.000Z,0,0
129,hardy_reza,@Dara_Cega inilah tololnya pejabat konoha... d...,2026-03-12T02:25:57.000Z,0,0
130,fadly_fadel,@IndonesiaFedera Bodoh!! Koruptor dibela &amp;...,2026-03-12T02:24:42.000Z,0,0
131,ANTARABengkulu,Komisi Pemberantasan Korupsi (KPK) menyita uan...,2026-03-12T02:19:38.000Z,0,0
132,ngekaoo98_owei,@DPR_RI KALO BELI MOBIL DOMESTIK KE PRODUSEN L...,2026-03-12T02:17:37.000Z,0,0
133,lpp_bandung,Lapas Perempuan Kelas IIA Bandung memperoleh h...,2026-03-12T02:16:46.000Z,0,0
134,fuckatharimau,"sumpah kalo dipikir pikir ini lucu banget, ada...",2026-03-12T02:15:54.000Z,0,0
135,Aboy1945,@mangkleke @UmarHasibuan__ @KPK_RI Nanti kalo ...,2026-03-12T02:14:46.000Z,1,0
136,JDIHKPUSLEMAN,Sebagai upaya dalam meningkatkan integritas pe...,2026-03-12T02:14:11.000Z,0,0
137,WillyUK777,@KuntoAjiW @adith_wp Mau pake bujer sebanyak a...,2026-03-12T02:11:42.000Z,0,0
138,ANTARABengkulu,Komisi Pemberantasan Korupsi (KPK) memanggil m...,2026-03-12T02:10:27.000Z,0,0
139,kantahlabusel,Hallo #sobatrbpn #kantahkablabusel\n\nSelama b...,2026-03-12T02:10:08.000Z,0,0
140,Di4ntara,@ImamBesar212 Penampilan seseorang bukan jamin...,2026-03-12T02:08:57.000Z,0,0
141,punishe98373138,@ecosocrights Hentikan MBG! Ganti dgn program ...,2026-03-12T02:08:33.000Z,0,0
142,ANTARABengkulu,Komisi Pemberantasan Korupsi (KPK) mengatakan ...,2026-03-12T02:08:03.000Z,0,0
143,Ay09359469,@Stakof yg satu pernah di panggil KPK sbg saks...,2026-03-12T02:06:55.000Z,0,0
144,GYatmoko,"@kompascom Kami orang tua dari anak2, juga min...",2026-03-12T02:06:30.000Z,0,0
145,AliMunt41989560,"@kompascom Urusan khusus,angkaylahi pejabat ba...",2026-03-12T02:04:37.000Z,0,0
146,pikiran_rakyat,Presiden Prabowo Subianto menegaskan komitmenn...,2026-03-12T02:02:49.000Z,1,0
147,AnakLurahIstana,@watchdoc_ID - dana desa\n- Bansos\n- kop mera...,2026-03-12T02:00:01.000Z,0,0
148,SultanH04160212,MBG tidak bergizi dan ladang korupsi serta mal...,2026-03-12T01:59:14.000Z,0,0
149,aokipay12,@secretbutmain_ Berarti kek gini boleh di kata...,2026-03-12T01:54:10.000Z,0,0
150,azizal_17,@_jahenal terang2 an banget og anjer neg rep k...,2026-03-12T01:52:45.000Z,0,0
151,lost466270,@Heraloebss Banyak baca berita ya kalian. Itu ...,2026-03-12T01:52:27.000Z,0,0
152,SangGuru2471,@kompascom Betul.\nDari dulu juga korupsi suda...,2026-03-12T01:52:12.000Z,0,0
153,CKumplang,@Marbot_Udien @DoroCah26424 Gaya hidupnya yang...,2026-03-12T01:50:47.000Z,2,2
154,DoroCah26424,@Marbot_Udien Fadia Arafiq menjadi buah bibir ...,2026-03-12T01:48:17.000Z,2,2
155,AdheMajid53508,@SemuaOKE710920 @tekarok007 Korupsi yg sudah T...,2026-03-12T01:45:58.000Z,0,0
156,akuratco,Komisi Pemberantasan Korupsi (KPK) menduga Bup...,2026-03-12T01:45:00.000Z,0,0
157,HumasKotabaru,"Pelayanan Polri yang ramah, cepat, mudah dan b...",2026-03-12T01:43:26.000Z,0,0
158,bapaspamekasan,Bapas Pamekasan mengikuti Sosialisasi Pelaksan...,2026-03-12T01:42:58.000Z,1,0
159,lpp_bandung,Lapas Perempuan Kelas IIA Bandung memperoleh h...,2026-03-12T01:42:25.000Z,0,0
160,rutantrenggalek,Hasil Survei Presepsi Anti Korupsi (SPAK) dan ...,2026-03-12T01:41:45.000Z,0,0
161,__SudutPandang,Program MBG tambang korupsi berkedok peduli an...,2026-03-12T01:40:53.000Z,0,0
162,humas_sarmi,"Terlaksanaya pelayan polribyang ramah, cepat,m...",2026-03-12T01:40:28.000Z,0,0
163,Oodhi_tah,@ArvinHonami @LaiElfrid Seperti lazimnya di Ko...,2026-03-12T01:37:57.000Z,3,0
164,VIVAcoid,Polisi Pastikan Pensiunan JICT Dibunuh Perampo...,2026-03-12T01:37:48.000Z,0,0
165,SangGuru2471,"@yusuf_dumdum Negara yang umatnya gampang ""dib...",2026-03-12T01:37:36.000Z,1,0
166,Lyraauliakss,KORUPSI WAKTU! @CommuterLine dari 8.20 ke 8.40...,2026-03-12T01:37:31.000Z,0,0
167,Apanamanya34711,"@xendless_s Untung besar pengelola dapur mbg, ...",2026-03-12T01:37:03.000Z,0,0
168,Mahfuzharmia,@BaseBDG The real korupsi dalam rumah tangga 😂,2026-03-12T01:36:48.000Z,0,0
169,WatesRutan,Hasil Survei SURVEI PERSEPSI KUALITAS PELAYANA...,2026-03-12T01:36:10.000Z,0,0
170,tejo2015,@msaid_didu @prabowo abs apanya bro?😂...siapa ...,2026-03-12T01:34:45.000Z,6,0
171,Muhamma54324201,@is_pelssy @liaasister Tuntut mati tuh yg koru...,2026-03-12T01:34:45.000Z,0,0
172,Apanamanya34711,@secretbutmain_ Hasil korupsi jatah siswa..? P...,2026-03-12T01:32:54.000Z,0,0
173,danurespati,@ImamBesar212 tidaklah korupsi orang yang koru...,2026-03-12T01:32:44.000Z,0,0
174,rizqie_1986,@lantip Pengen ngerti jika banyak fungsi yg ri...,2026-03-12T01:31:35.000Z,0,0
175,kupihitampahit,@UmarHasibuan__ @KPK_RI Pelaku Dari kalangan u...,2026-03-12T01:29:59.000Z,0,0
176,anando15,@AyatulH86561504 @PngAdilnR4kyt @grok GAK BISA...,2026-03-12T01:28:43.000Z,0,0
177,fajarhut99,@UmarHasibuan__ @KPK_RI Hukum seumur hidup dan...,2026-03-12T01:26:43.000Z,0,0
178,hariankompas,OTT KPK terhadap Bupati Rejang Lebong Muhammad...,2026-03-12T01:26:39.000Z,0,0
179,ConservingWLife,@narkosun MBG itu kan proyek korupsi kenapa ga...,2026-03-12T01:25:40.000Z,0,0
180,KompasData,OTT KPK terhadap Bupati Rejang Lebong Muhammad...,2026-03-12T01:25:25.000Z,0,0
181,asfan_warah,@watchdoc_ID Segini parahnya budaya korupsi di...,2026-03-12T01:24:39.000Z,1,0
182,rwardoyo,@wagonrid kita ini bangsa kaya!!!\ngemah Ripah...,2026-03-12T01:23:22.000Z,0,0
183,Lyraauliakss,WOY KERETA LU KP.BANDA VIA SENEN KEMANAAAAAA Y...,2026-03-12T01:22:56.000Z,0,0
184,skdw94,Ini kayak kasus korupsi temenku soal catering....,2026-03-12T01:22:48.000Z,0,0
185,kompasmuda,OTT KPK terhadap Bupati Rejang Lebong Muhammad...,2026-03-12T01:22:13.000Z,0,0
186,kilabluebub,Nyoba nontonin salah 1 series indo. Terus di s...,2026-03-12T01:22:09.000Z,0,0
187,SemuaOKE710920,@tekarok007 @AdheMajid53508 Korupsi lebih gila...,2026-03-12T01:21:48.000Z,2,0
188,EastDawn2,@gegerriy Jangankan yg pegang bedil. Yg sipil ...,2026-03-12T01:20:58.000Z,6,0
189,melati_puspita9,@GenZNusantara Pemberantasan korupsi ala Presi...,2026-03-12T01:20:27.000Z,0,0
190,Irwanyh0,@PresidenKopi goblok ya korupsi lah,2026-03-12T01:19:18.000Z,0,0
191,achmad_ala78284,@Hnirankara Sekarang anggota NU kok banyak yg ...,2026-03-12T01:17:46.000Z,0,0
192,hariankompas,OTT KPK terhadap Bupati Rejang Lebong Muhammad...,2026-03-12T01:16:32.000Z,0,0
193,KompasData,OTT KPK terhadap Bupati Rejang Lebong Muhammad...,2026-03-12T01:13:44.000Z,0,0
194,Eko_a7,@KuntoAjiW Duit korupsi mbg dipake buat bayar bot,2026-03-12T01:12:38.000Z,0,0
195,sashasmaaku,@secretbutmain_ Jujur emang korupsi nya ada ba...,2026-03-12T01:10:17.000Z,0,0
196,RonadiRona68663,"@YanSanaky @ImamBesar212 Botol otak ga nyampe,...",2026-03-12T01:07:23.000Z,9,0
197,Saylocho,@kenhans03 Waduh bupati titipan gak ini? Kalau...,2026-03-12T01:05:45.000Z,0,0
198,Montir_UFO,@msaid_didu Ketiga lembaga itu dipastikan tida...,2026-03-12T01:05:05.000Z,0,0
199,RadioElshinta,Mantan pimpinan Komisi Pemberantasan Korupsi (...,2026-03-12T01:03:35.000Z,1,0
200,noezxcvbnm,@GunRomli Biasanya yang teriak teriak ada koru...,2026-03-12T00:26:23.000Z,0,0
201,oktasardhy,@narkosun Bro cosplay jadi malaikat izroil 🙏🏼 ...,2026-03-12T00:25:04.000Z,0,0
202,AliminVellan,"@Tumini_Ball E katalog ini aneh, tujuan supaya...",2026-03-12T00:22:22.000Z,0,0
203,IGNB07,https://t.co/kxIc5omI1d\nMemang sangatlah dise...,2026-03-12T00:21:23.000Z,0,0
204,jharmeini,@IndonesiaFedera Kalau cuma JAWA yg di pikirka...,2026-03-12T00:20:28.000Z,3,0
205,RadioElshinta,Polda Metro Jaya tahan tersangka dugaan korups...,2026-03-12T00:20:00.000Z,1,0
206,layar099,@Bambangmulyonoo Di tipu no 2\nRakyat miskin n...,2026-03-12T00:17:19.000Z,0,0
207,kadoel,@DianSandiU MBG nyatanya jadi ajang bancaan ko...,2026-03-12T00:16:36.000Z,0,0
208,Hendra619422,@KangManto123 Inilah kalau korupsi di buat ber...,2026-03-12T00:16:05.000Z,0,0
209,lurahKebon72293,@UmarHasibuan__ @KPK_RI Ini manusia kalau deba...,2026-03-12T00:16:03.000Z,0,0

### **Simpan File**

In [ ]:
data_x.to_excel("scraping_x.xlsx")